services:
    nicofuma.debugtools.console.command.cache.get:
        class: nicofuma\debugtools\console\command\cache\get
        arguments:
            - @user
            - @cache.driver
        tags:
            - { name: console.command }

    nicofuma.debugtools.console.command.container.debug:
        class: nicofuma\debugtools\console\command\container\debug
        arguments:
            - @user
            - @config.php
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: console.command }

    nicofuma.debugtools.console.command.router.debug:
        class: nicofuma\debugtools\console\command\router\debug
        arguments:
            - @user
            - @controller.provider
        tags:
            - { name: console.command }
